import os
import raylibpy
MAX_X = 1000
MAX_Y = 800
FRAME_RATE = 60

DEFAULT_SQUARE_SIZE = 20
DEFAULT_FONT_SIZE = 20
DEFAULT_TEXT_OFFSET = 4

PLAYER_WIDTH = 40
PLAYER_HEIGHT = 40
PLAYER_SPEED = 6
PLAYER_COLOR = raylibpy.BLUE
PLAYER_INV_COLOR = raylibpy.WHITE
PLAYER_DEAD_COLOR = raylibpy.DARKGRAY

WALL_COLOR = raylibpy.GRAY
PLATFORM_COLOR = raylibpy.LIGHTGRAY

BULLET_WIDTH = 20
BULLET_HEIGHT = 20
BULLET_COLOR = raylibpy.YELLOW
BULLET_SPEED = 10

JUMP_SPEED = 1
GRAVITY = 1
JUMP_TIME = 0.3
SHOOT_TIME = 0.15
INVINCIBLE_TIME = 2

ENEMY_WIDTH = 40
ENEMY_HEIGHT = 40
ENEMY_COLOR = raylibpy.RED

WALKER_SPEED = 2
WALKER_JUMP_SPEED = 1
WALKER_JUMP_TIME = 1
WALKER_COOLDOWN = 0.4
