import os
import raylibpy
MAX_X = 1000
MAX_Y = 800
FRAME_RATE = 60

DEFAULT_SQUARE_SIZE = 20
DEFAULT_FONT_SIZE = 20
DEFAULT_TEXT_OFFSET = 4

PLAYER_WIDTH = 40
PLAYER_HEIGHT = 40
PLAYER_SPEED = 6
PLAYER_COLOR = raylibpy.BLUE

WALL_WIDTH = 40
WALL_HEIGHT = 40
WALL_COLOR = raylibpy.GRAY

BULLET_WIDTH = 20
BULLET_HEIGHT = 20
BULLET_COLOR = raylibpy.RED
BULLET_SPEED = 10

JUMP_TIME = 0.3
SHOOT_TIME = 0.15